import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/navigation";
import { montserratAlternates, albertSans } from '@/lib/fonts';
import Footer from "./components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-[80%]">
      <body className={`${montserratAlternates.className} ${albertSans.className} h-full`} >
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
